name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Recreate Android Project Files
        run: |
          flutter create . --org hk.edu.tkp --project-name tkp_english

      - name: Get Dependencies
        run: flutter pub get

      # 使用標準建置參數指定 min-sdk-version 為 21
      - name: Build APK
        run: flutter build apk --release --min-sdk-version 21

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tkp-english-app
          path: build/app/outputs/flutter-apk/app-release.apk
